### ISSUE TITLE
rake protractor:spec_and_cleanup doesn't actually run cleanup

### ISSUE THREAD

**Issue by sambou** [tyronewilson/protractor-rails#19]
Hey,
when running rake protractor:spec_and_cleanup, it only runs spec on my machine. Running cleanup manually afterwards works (db gets seeded correctly), however this doesn't seem to be the intended behaviour.
I'm wondering if maybe i'm doing sth. wrong or this is a legit issue. Let me know if you need more information/logs/etc.
Cheers,
Sami

**Comment by tyronewilson** [comment]
Awesome. Thanks!

**Comment by fdibartolo** [comment]
Hey guys, I have just submitted [pull request #24](https://github.com/tyronewilson/protractor-rails/pull/24) which I believe should take care of this issue. What I am seeing is that `spec` task is always running system exit, preventing `cleanup` task to actually run afterwards.
