### ISSUE TITLE
Cannot run single protractor tests

### ISSUE THREAD

**Issue by map7** [tyronewilson/protractor-rails#25]
I've recently upgrade from rake 10.3.2 to 10.4.2 and can no longer run single tests using the following

    bundle exec rake protractor:spec -- --specs spec/javascripts/protractor_specs/users/edit_users_spec.js.coffee

**Comment by fdibartolo** [comment]
from the doc: _NOTE You must have the -- first otherwise rake will think the arguments are for rake instead of the task_

`bundle exec rake protractor:spec -- --specs [filepath]` should work.

**Comment by map7** [comment]
I am using that syntax and having problems, it just ends up doing all the tests (with rake 10.4.x, but it works with rake 10.3.2)

**Comment by tyronewilson** [comment]
Could this be related to https://github.com/ruby/rake/issues/11?

**Comment by map7** [comment]
Hmm, I don't get any OptionParser error like he does, it just doesn't see the '-- specs [filepath]' when I use rake 10.4.2. If I try and run just one spec it ends up testing all my protractor specs.

**Comment by tyronewilson** [comment]
Did you ever get to the bottom of this @map7?

**Comment by map7** [comment]
No unfortunately I'm still on rake 10.3.2 to get around this problem. It's not a good fix.

**Comment by jonricaurte** [comment]
Yep, this does not work.

**Comment by ProGM** [comment]
@tyronewilson What about changing syntax in something like:
```ruby
bundle exec rake protractor:spec SPECS=spec/javascripts/protractor_specs/users/edit_users_spec.js.coffee
```

This should work, using `ENV['SPECS']` to get the parameter.

For example, rake db:rollback uses this strategy to pass parameters...

```ruby
rake db:rollback STEP=1
```

**Comment by tyronewilson** [comment]
We could certainly see how it does. Have you got something like this working locally?

**Comment by ProGM** [comment]
I did a try, check it please #45 :)

**Comment by tyronewilson** [comment]
@map7 can you check this fix for your scenario?

**Comment by avel** [comment]
I know this is an old issue, but the alternative ENV-based argument passing worked for me, so you could consider closing this bug.

The question now is, how about any other argument that we may want to pass over to protractor through rake? For instance, how can I start `protractor --elementExplorer`?

**Comment by map7** [comment]
Thanks guys. Just upgraded the package on this old project and it works.

**Comment by avel** [comment]
Nice. And I added temporarily the line

```
      options += " #{ENV['PROTRACTOR_OPTS']}" if ENV['PROTRACTOR_OPTS'].present?
```

for any other arguments I might want to pass, until I upgrade rake or something...

**Comment by tyronewilson** [comment]
If it's useful why not submit a Pr for that?
