### ISSUE TITLE
Problem with rake protractor:install

### ISSUE THREAD

**Issue by micahbolen** [tyronewilson/protractor-rails#26]
I have already installed the gem locally into my project, but when I run `rake protractor:install`, I get this message:

`Don't know how to build task 'protractor:install'`

Any ideas?

**Comment by tyronewilson** [comment]
have you tried running bundle exec in front of that. Sounds to me like perhaps you are using a different gemset or something or you installed it under the system gems using `sudo` or something like that. What do you get if you run gem list `protractor-rails`?

**Comment by micahbolen** [comment]
Thanks, Tyrone.  I'm pretty sure it's just a configuration/environment problem on my end.  Cheers!

**Comment by tyronewilson** [comment]
Cool well let us know if you don't come right. Cheers

**Comment by bramski** [comment]
I have this same problem.  On Rails 3.2.21, Rake 10.4.2.
![screen shot 2015-02-09 at 7 46 43 pm](https://cloud.githubusercontent.com/assets/421781/6121263/67344828-b094-11e4-9db4-24ceb47b123d.png)

**Comment by bramski** [comment]
Ahh. The problem is where you would naturally want to place this task is in ```group :test```.  Default environment is 'dev' so the task won't show up.
