### ISSUE TITLE
kill_server not working when using unicorn as server

### ISSUE THREAD

**Issue by ProGM** [tyronewilson/protractor-rails#33]
After running `rake protractor:spec` I have to kill manually the server.

```bash
ps aux | grep rails | awk '{print $2}' | xargs kill -QUIT &> /dev/null
```

I'm using unicorn as default server (rails server starts unicorn).

**Comment by ProGM** [comment]
This seems to work if using the HEAD of the repo, using:

```ruby
  gem 'protractor-rails', github: 'tyronewilson/protractor-rails'
```

**Comment by tyronewilson** [comment]
there should be no difference between master and version 0.0.14. Have you tried running `bundle update protractor-rails` instead of using the repo directly?

**Comment by ProGM** [comment]
@tyronewilson 
In my Gemfile.lock I have:

```
protractor-rails (0.0.14)
```

But, navigating in vendor/bundle/ruby/2.2.0/protractor-rails-0.0.14/lib/tasks/protractor.rake, like 89, I find:

```ruby
  task :kill_rails do
    write_log "kill protractor rails tests server...".yellow
    system "ps aux | grep -ie 'rails s -e test -P tmp/pids/protractor_test_server.pid --port=#{Protractor.configuration.port}' | grep -v grep | awk '{print $2}' | xargs kill -9"
  end
```

Instead of:
```ruby
  task :kill_rails do
    write_log "kill protractor rails tests server...".yellow
    system "kill `cat tmp/pids/protractor_test_server.pid`"
  end
```

Are you sure that there is no difference between 0.0.14 and HEAD?

**Comment by tyronewilson** [comment]
seems not. I will update and release new version. Thanks for finding this.

**Comment by ProGM** [comment]
Thank you!

**Comment by tyronewilson** [comment]
please update to version 0.0.15 and let me know if you have any issues
