### ISSUE TITLE
rake protractor:example failing

### ISSUE THREAD

**Issue by itsryandrake** [tyronewilson/protractor-rails#34]
Hi,

I'm running 'rake protractor:example' but it's failing because it's telling me I need to install Java.

Except, I've already done that and tested it works in Safari! Java 8.

Any luck or suggestions with how to get the example running?

**Comment by itsryandrake** [comment]
I figured out what the issue was here! Didn't init.

**Comment by tyronewilson** [comment]
Glad to have helped. :)
