### ISSUE TITLE
add --standalone flag

### ISSUE THREAD

**Issue by jonricaurte** [tyronewilson/protractor-rails#42]
Can you add --standalone flag here?

https://github.com/tyronewilson/protractor-rails/blob/master/lib/tasks/protractor.rake#L106

Seems like it will randomly fail with new version of protractor if this flag is left out:

http://stackoverflow.com/questions/20055593/unable-to-run-protractor-econnrefused-connect-econnrefused

**Comment by tyronewilson** [comment]
Feel free to add a pull request :)

**Comment by jonricaurte** [comment]
https://github.com/tyronewilson/protractor-rails/pull/43/files

**Comment by jonricaurte** [comment]
Added a pr for it. Thanks!

**Comment by tyronewilson** [comment]
merged and released as `0.0.16`

**Comment by jonricaurte** [comment]
Thanks!
